pub mod accordion;
pub mod alert_dialog;
pub mod autocomplete;
pub mod avatar;
pub mod button;
pub mod checkbox;
pub mod checkbox_group;
pub mod collapsible;
pub mod combobox;
pub mod context_menu;
pub mod dialog;
pub mod drawer;
pub mod field;
pub mod fieldset;
pub mod form;
pub mod input;
pub mod menu;
pub mod menubar;
pub mod meter;
pub mod navigation_menu;
pub mod number_field;
pub mod otp_field;
pub mod popover;
pub mod preview_card;
pub mod primitives;
pub mod progress;
pub mod radio_group;
pub mod scroll_area;
pub mod select;
pub mod separator;
pub mod slider;
pub mod switch;
pub mod tabs;
pub mod toast;
pub mod toggle;
pub mod toggle_group;
pub mod toolbar;
pub mod tooltip;
pub mod utils;

pub fn init(cx: &mut gpui::App) {
    accordion::init(cx);
    alert_dialog::init(cx);
    button::init(cx);
    checkbox::init(cx);
    checkbox_group::init(cx);
    collapsible::init(cx);
    combobox::init(cx);
    dialog::init(cx);
    fieldset::init(cx);
    form::init(cx);
    menu::init(cx);
    menubar::init(cx);
    navigation_menu::init(cx);
    number_field::init(cx);
    otp_field::init(cx);
    popover::init(cx);
    preview_card::init(cx);
    primitives::input::init(cx);
    radio_group::init(cx);
    select::init(cx);
    slider::init(cx);
    switch::init(cx);
    tabs::init(cx);
    toast::init(cx);
    toggle::init(cx);
    toggle_group::init(cx);
    toolbar::init(cx);
    tooltip::init(cx);
}
